# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-04 08:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu1', models.CharField(max_length=20)),
                ('menu2', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='res',
            name='version',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='meun',
            name='res',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.Res'),
        ),
    ]
