# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-04 08:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_auto_20160404_1602'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='res',
            options={'ordering': ['name']},
        ),
    ]
